import {
  Archive,
  ArrowLeft,
  Banknote,
  BarChart3,
  Bell,
  Calculator,
  Calendar,
  CalendarCheck,
  Car,
  ChartNoAxesColumn,
  Check,
  CheckCheck,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleUser,
  ClipboardCheck,
  Clock,
  Coins,
  Copy,
  CreditCard,
  Droplet,
  Droplets,
  Eye,
  EyeOff,
  Factory,
  FileDown,
  FileInput,
  FileOutput,
  FileSpreadsheet,
  FileWarning,
  Filter,
  Flag,
  FolderOpen,
  Fuel,
  Gauge,
  Home,
  Image,
  Info,
  Key,
  Keyboard,
  Landmark,
  Languages,
  Layers,
  LineChart,
  List,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  LogOut,
  MapPin,
  Menu,
  Moon,
  MoreHorizontal,
  MoreVertical,
  PanelLeftClose,
  PanelLeftOpen,
  ParkingCircle,
  Pencil,
  Plus,
  Puzzle,
  Receipt,
  RefreshCw,
  Repeat,
  Route,
  Save,
  Scale,
  Server,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  SquarePen,
  Star,
  StickyNote,
  Sun,
  Tags,
  Trash2,
  TriangleAlert,
  Users,
  Wallet,
  WandSparkles,
  Warehouse,
  Wrench,
  X,
} from 'lucide-react'

const ICONS = {
  archive: Archive,
  arrowLeft: ArrowLeft,
  banknote: Banknote,
  barChart: BarChart3,
  bell: Bell,
  calculator: Calculator,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  car: Car,
  chart: ChartNoAxesColumn,
  check: Check,
  checkCheck: CheckCheck,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  circleHelp: CircleHelp,
  circleUser: CircleUser,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  coins: Coins,
  copy: Copy,
  creditCard: CreditCard,
  droplet: Droplet,
  droplets: Droplets,
  eye: Eye,
  eyeOff: EyeOff,
  factory: Factory,
  fileDown: FileDown,
  fileInput: FileInput,
  fileOutput: FileOutput,
  fileSpreadsheet: FileSpreadsheet,
  fileWarning: FileWarning,
  filter: Filter,
  flag: Flag,
  folderOpen: FolderOpen,
  fuel: Fuel,
  gauge: Gauge,
  home: Home,
  image: Image,
  info: Info,
  key: Key,
  keyboard: Keyboard,
  landmark: Landmark,
  languages: Languages,
  layers: Layers,
  lineChart: LineChart,
  list: List,
  listChecks: ListChecks,
  listOrdered: ListOrdered,
  loader: LoaderCircle,
  logOut: LogOut,
  mapPin: MapPin,
  menu: Menu,
  moon: Moon,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  parking: ParkingCircle,
  pencil: Pencil,
  plus: Plus,
  puzzle: Puzzle,
  receipt: Receipt,
  refresh: RefreshCw,
  repeat: Repeat,
  route: Route,
  save: Save,
  scale: Scale,
  server: Server,
  settings: Settings,
  shield: Shield,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  squarePen: SquarePen,
  star: Star,
  stickyNote: StickyNote,
  sun: Sun,
  tags: Tags,
  trash: Trash2,
  triangleAlert: TriangleAlert,
  users: Users,
  wallet: Wallet,
  wand: WandSparkles,
  warehouse: Warehouse,
  wrench: Wrench,
  x: X,
}

export default function Icon({ name, size = 18, className = '', spin = false }) {
  const Cmp = ICONS[name]
  if (!Cmp) return null
  return (
    <Cmp
      size={size}
      strokeWidth={1.75}
      className={`${className}${spin ? ' icon-spin' : ''}`.trim()}
      aria-hidden="true"
    />
  )
}

export function recordIconName(tipo) {
  const t = String(tipo || '').toLowerCase()
  if (t.includes('abastecimento')) return 'fuel'
  if (t.includes('fipe')) return 'tags'
  if (t.includes('manutenção')) return 'wrench'
  if (t.includes('multa')) return 'fileWarning'
  return 'wallet'
}
